### ISSUE TITLE
Documentação da Interface

### ISSUE THREAD

**Issue by JoaoGFarias** [pbsf/Indexed-Pattern-Matching-Tool#1]
Sendo trackeada na [Wiki do projeto](https://github.com/pbsf/Indexed-Pattern-Matching-Tool/wiki/POSIX-Interface)

**Comment by JoaoGFarias** [comment]
Sugestão de biblioteca para lidar com a CLI: [Google GFlags](https://github.com/gflags/gflags)
Portável :+1:

**Comment by pbsf** [comment]
Acabei optando por getOpt mesmo. Como são poucas flags (5) achei que não ia precisar de uma biblioteca externa.
