### ISSUE TITLE
Definição do framework de teste unitário

### ISSUE THREAD

**Issue by JoaoGFarias** [pbsf/Indexed-Pattern-Matching-Tool#2]
Depois de uma rápida pesquisa, não achei nenhum framework de testes unitários C++ com instalação e uso. Apesar de achar que para nosso software não é necessário o uso de um framework (principalmente depois que a [interface estiver definida](https://github.com/pbsf/Indexed-Pattern-Matching-Tool/issues/1), mas se tivermos isso setado, já mitigamos qualquer risco.

@rmf4 e @pbsf, vocês tem alguma sugestão nessa questão?

**Comment by pbsf** [comment]
Também não conheço nenhum framework. Eu acho que o mais ideal, que inclusive já estou fazendo no lz78, é criar testes para cada algoritmo na própria classe no algorítmo, ou em uma classe auxiliar.
